[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_OPTIONAL = "true"
  CI = "true"

# Production environment variables
[context.production.environment]
  VITE_API_BASE = ""
  VITE_APP_NAME = "AgriAI Platform"
  VITE_ENABLE_ANALYTICS = "true"
  VITE_DEBUG_MODE = "false"

# Deploy preview environment variables  
[context.deploy-preview.environment]
  VITE_API_BASE = ""
  VITE_DEBUG_MODE = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200